spring.application.name=mybar

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/usuarios?createDatabaseIfNotExist=true
spring.datasource.username=dev
spring.datasource.password=Dev@123
